### ISSUE TITLE
not working on IE11

### ISSUE THREAD

**Issue by majacal** [RobinL/d3_orgchart_yammer#2]
the text labels not working in IE11

![image](https://cloud.githubusercontent.com/assets/8426566/17184907/f1f2c7ac-542e-11e6-844f-c9ba4a8240e9.png)

is there a solution for that ?

**Comment by RobinL** [comment]
The issue here is that i use divs in foreign objects to hold the text, see:
https://github.com/RobinL/d3_orgchart_yammer/blob/master/website/js/main.js#L204

Unfortunately these don't display in IE.

I do this because it enables text wrapping, which is quite hard to achieve in standard svg text elements.

If you want to modify, you just need to alter it so that rather than using divs, it uses text elements, and you'll just have to put up with no text wrapping, or implement this yourself.

**Comment by majacal** [comment]
ok i tried this to fix ... but it wont work ... 

can u show me a code snippet how it works ... 

i know the script append a foreign-object ... that will not work in IE ... but how can i replace it to a text ?
